Middleware for protecting metrics endpoint
tlm-solutions/datacare pull request #29
Opened 2023-05-12 15:20 UTC by revol-xut

## Things Changed

## Required Doc/Changelog Updates

- [ ] **I HAVE UPDATED CHANGELOG ACCORDINGLY**
- [ ] **I HAVE UPDATED DOCS ACCORDINGLY**

2023-05-12 15:54 UTC, oxapentane requested changes
See comments

2023-05-12 15:54 UTC, oxapentane commented on flake.lock
Split out lock bumps to separate commit

2023-05-12 15:54 UTC, oxapentane commented on flake.nix
> +    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
Why? Our deployments are targeting stable. Also, not part of "implementing middleware"

2023-05-12 15:54 UTC, oxapentane commented on src/security.rs
> +            &std::env::var("PROMETHEUS_ALLOWED_IPS").unwrap_or("[\"10.13.37.0/24\"]".to_string()),
No defaults. Not configured -> all requests to the endpoint gracefully HTTP error out

2023-05-12 15:54 UTC, oxapentane commented on src/security.rs
> +            &std::env::var("PROMETHEUS_ALLOWED_IPS").unwrap_or("[\"10.13.37.0/24\"]".to_string()),
DATACARE_PROMETHEUS_ALLOWED_IPS

2023-05-12 15:54 UTC, oxapentane commented on src/security.rs
> +            .map(|x| x.parse().unwrap())
```suggestion
            .map(|x| x.parse().expect("meaningful error message"))
```

2023-05-12 15:54 UTC, oxapentane commented on src/security.rs
> +        .unwrap_or(vec!["10.13.37.0/24".to_string()]);
No defaults. Match, throw a warning, return HTTP error on any request to the endpoint

2023-05-12 15:56 UTC, revol-xut commented on flake.nix
> +    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
some of the crates need a very version of rust and this was the easiest to get it to build again.

2023-05-12 15:56 UTC, revol-xut commented on src/security.rs
> +            &std::env::var("PROMETHEUS_ALLOWED_IPS").unwrap_or("[\"10.13.37.0/24\"]".to_string()),
So u just want an expect(...) ?

2023-05-12 15:57 UTC, revol-xut commented on src/security.rs
> +            &std::env::var("PROMETHEUS_ALLOWED_IPS").unwrap_or("[\"10.13.37.0/24\"]".to_string()),
fair

2023-05-12 16:17 UTC, oxapentane commented on src/security.rs
> +            &std::env::var("PROMETHEUS_ALLOWED_IPS").unwrap_or("[\"10.13.37.0/24\"]".to_string()),
also possible, like if we want to just configure nothing or hard fail (expect) on missing config - up to you

2023-05-12 18:14 UTC, oxapentane requested changes
fix the history

2023-05-13 13:21 UTC, oxapentane approved these changes

2023-05-13 13:21 UTC, merged